# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [1]:
# import libraries
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# load messages dataset
messages = pd.read_csv("messages.csv")
messages.head(20)

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct
5,14,Information about the National Palace-,Informtion au nivaux palais nationl,direct
6,15,Storm at sacred heart of jesus,Cyclone Coeur sacr de jesus,direct
7,16,"Please, we need tents and water. We are in Sil...",Tanpri nou bezwen tant avek dlo nou zon silo m...,direct
8,17,"I would like to receive the messages, thank you",Mwen ta renmen jouin messag yo. Merci,direct
9,18,I am in Croix-des-Bouquets. We have health iss...,"Nou kwadebouke, nou gen pwoblem sant m yo nan ...",direct
10,20,"There's nothing to eat and water, we starving ...",Bon repo pa gen anyen menm grangou swaf,direct
11,21,I am in Petionville. I need more information r...,M nan pv mvle plis enfomasyon sou 4636,direct
12,22,"I am in Thomassin number 32, in the area named...",Mwen thomassin 32 nan pyron mwen ta renmen jwe...,direct
13,24,"Let's do it together, need food in Delma 75, i...",Ann fel ansanm bezwen manje nan delma 75 nan r...,direct
14,25,More information on the 4636 number in order f...,gen plis enfomasyon sou 4636 la pom w sim ap k...,direct
15,26,"A Comitee in Delmas 19, Rue ( street ) Janvier...",Komite katye delma 19 rue janvier imp charite ...,direct
16,27,We need food and water in Klecin 12. We are dy...,Nou bezwen mange avek dlo nan klcin 12 LA LAFI...,direct
17,28,are you going to call me or do you want me to ...,Eske se rele nap relem oubyen se mwen kap rele...,direct
18,30,I don't understand how to use this thing 4636.,Mwen pa konprann koman pou m itilize bagay 463...,direct
19,31,I would like to know if the earthquake is over...,Mwen ta remen connin si trenblem de terre afin...,direct

In [3]:
# load categories dataset
categories = pd.read_csv('categories.csv')
categories.head()

   id                                         categories
0   2  related-1;request-0;offer-0;aid_related-0;medi...
1   7  related-1;request-0;offer-0;aid_related-1;medi...
2   8  related-1;request-0;offer-0;aid_related-0;medi...
3   9  related-1;request-1;offer-0;aid_related-1;medi...
4  12  related-1;request-0;offer-0;aid_related-0;medi...

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [4]:
# merge datasets
df = messages.merge(categories, on="id")
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [5]:
# create a dataframe of the 36 individual category columns
categories = df['categories'].str.split(pat = ";", expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [6]:
# select the first row of the categories dataframe
row = categories.iloc[0]
row
# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = row.apply(lambda x: x[:-2])
print(category_colnames)

0                    related
1                    request
2                      offer
3                aid_related
4               medical_help
5           medical_products
6          search_and_rescue
7                   security
8                   military
9                child_alone
10                     water
11                      food
12                   shelter
13                  clothing
14                     money
15            missing_people
16                  refugees
17                     death
18                 other_aid
19    infrastructure_related
20                 transport
21                 buildings
22               electricity
23                     tools
24                 hospitals
25                     shops
26               aid_centers
27      other_infrastructure
28           weather_related
29                    floods
30                     storm
31                      fire
32                earthquake
33                      cold
34             other_weather
35             direct_report
Name: 0, dtype: object

In [7]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [8]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].apply(lambda x: x[-1])
    
    # convert column from string to numeric
    categories[column] = pd.to_numeric(categories[column])
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [9]:
# drop the original categories column from `df`
df = df.drop(columns="categories")

df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [10]:
# concatenate the original dataframe with the new `categories` dataframe
df = pd.concat([df, categories], axis=1)
#df.head()
df.head(30)

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,14,Information about the National Palace-,Informtion au nivaux palais nationl,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,15,Storm at sacred heart of jesus,Cyclone Coeur sacr de jesus,direct,1,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
7,16,"Please, we need tents and water. We are in Sil...",Tanpri nou bezwen tant avek dlo nou zon silo m...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,17,"I would like to receive the messages, thank you",Mwen ta renmen jouin messag yo. Merci,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,18,I am in Croix-des-Bouquets. We have health iss...,"Nou kwadebouke, nou gen pwoblem sant m yo nan ...",direct,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1
10,20,"There's nothing to eat and water, we starving ...",Bon repo pa gen anyen menm grangou swaf,direct,1,1,0,1,1,1,...,0,1,1,1,0,0,0,0,0,1
11,21,I am in Petionville. I need more information r...,M nan pv mvle plis enfomasyon sou 4636,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,22,"I am in Thomassin number 32, in the area named...",Mwen thomassin 32 nan pyron mwen ta renmen jwe...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
13,24,"Let's do it together, need food in Delma 75, i...",Ann fel ansanm bezwen manje nan delma 75 nan r...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
14,25,More information on the 4636 number in order f...,gen plis enfomasyon sou 4636 la pom w sim ap k...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,26,"A Comitee in Delmas 19, Rue ( street ) Janvier...",Komite katye delma 19 rue janvier imp charite ...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
16,27,We need food and water in Klecin 12. We are dy...,Nou bezwen mange avek dlo nan klcin 12 LA LAFI...,direct,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
17,28,are you going to call me or do you want me to ...,Eske se rele nap relem oubyen se mwen kap rele...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,30,I don't understand how to use this thing 4636.,Mwen pa konprann koman pou m itilize bagay 463...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,31,I would like to know if the earthquake is over...,Mwen ta remen connin si trenblem de terre afin...,direct,1,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
20,32,I would like to know if one of the radio ginen...,Mwen ta renmen konnen eske ge jounalis radyo g...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,33,"I'm in Laplaine, I am a victim",Mwen laplan mwen viktim kot yap bay d pou latr...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
22,34,"There's a lack of water in Moleya, please info...",Nan moleya pa gen dlo svp f konnen sa pou mwen.,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
23,35,Those people who live at Sibert need food they...,nou menm nan sibert nou grangou nou bezwen mange,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24,36,"I want to say hello, my message is to let you ...",Mwen salye nou dab mesaj mwen an se jis nou ge...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,37,Can you tell me about this service,Can you tell me about this service,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,38,"People I'm at Delma 2, we don't anything what ...",MEZANMI MWEN MWEN NAN DELMA 2 NOU TR MAN MAL N...,direct,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1
27,39,We are at Gressier we needs assistance right a...,Se gressier nou an difikilte tanpri vin ede nou,direct,1,1,0,1,1,0,...,0,0,1,1,0,0,0,0,0,1
28,41,How can we get water and food in Fontamara 43 ...,Comment nou ka jwen dlo ak manje nan font 43 c...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
29,42,We need help. Carrefour has been forgotten com...,Nap di secours yo bliye kafou net sant m ap to...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
df.groupby('genre').count()['message']

genre
direct    10852
news      13128
social     2406
Name: message, dtype: int64

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [12]:
# check number of duplicates
df[df.duplicated()]

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
164,202,?? port au prince ?? and food. they need gover...,p bay pap la syen ak manje. Yo bezwen ed gouve...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
165,202,?? port au prince ?? and food. they need gover...,p bay pap la syen ak manje. Yo bezwen ed gouve...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
658,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
659,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
660,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
715,862,What is the address of the radio station? I as...,Ki adres radyo a? Paske m bezwen al depoze dos...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
716,862,What is the address of the radio station? I as...,Ki adres radyo a? Paske m bezwen al depoze dos...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1415,1652,"please we need water, food and tents, we have ...","p jwen dlo, manje, tant pou nou demi nou gen 1...",direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1416,1652,"please we need water, food and tents, we have ...","p jwen dlo, manje, tant pou nou demi nou gen 1...",direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2139,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2140,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2141,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2803,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2804,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2805,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2838,3250,I thought you gave my number and this was seri...,Mwen tepanse le nou tebay nimewo a se yon afse...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2839,3250,I thought you gave my number and this was seri...,Mwen tepanse le nou tebay nimewo a se yon afse...,direct,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3389,3882,"I am in Carefour Feuilles, Dkayet neighborhood...",Mwen nan kafou fy zon dekayt nou beswen dlo po...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3390,3882,"I am in Carefour Feuilles, Dkayet neighborhood...",Mwen nan kafou fy zon dekayt nou beswen dlo po...,direct,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
3868,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3869,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3870,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4360,4956,"What we saw yesterday is a sign, you need to k...",a nou w la yo se sign yoy ou bezwen kon sa Jez...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4361,4956,"What we saw yesterday is a sign, you need to k...",a nou w la yo se sign yoy ou bezwen kon sa Jez...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4543,5153,there are people in Delmas 32 who form an asso...,Ginyin yon paket moun delmas 32 ki forme organ...,direct,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4544,5153,there are people in Delmas 32 who form an asso...,Ginyin yon paket moun delmas 32 ki forme organ...,direct,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4652,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4653,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4654,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4917,5573,"If I would like to find a job in cepoz, what s...",Si mwen ta renmen jwen travay nan cepoz ki sa ...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20073,23229,* German Agro Action (GAA) reported that in th...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20991,24247,"As we approach Luabo, I get my first impressio...",NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20992,24247,"As we approach Luabo, I get my first impressio...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
21083,24347,In response to North Korea's devastating artil...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
21084,24347,In response to North Korea's devastating artil...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
21477,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21478,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21479,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21480,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21481,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21482,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21483,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21484,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
22153,25512,The flood situation has worsened with nearly 3...,NaN,news,1,0,0,1,0,0,...,0,1,1,1,0,0,0,0,0,0
22154,25512,The flood situation has worsened with nearly 3...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
23736,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23737,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23738,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24169,27768,An EU-backed French offensive against rebels r...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24170,27768,An EU-backed French offensive against rebels r...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24779,28462,"To date, a total of 39 people suffering from E...",NaN,news,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
24780,28462,"To date, a total of 39 people suffering from E...",NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
24988,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24989,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24990,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
25291,29022,"In a field in Jallouzai, just inside Pakistan,...",NaN,news,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
25292,29022,"In a field in Jallouzai, just inside Pakistan,...",NaN,news,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
25378,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25379,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25380,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# drop duplicates
df = df.drop_duplicates()

In [14]:
# check number of duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [id, message, original, genre, related, request, offer, aid_related, medical_help, medical_products, search_and_rescue, security, military, child_alone, water, food, shelter, clothing, money, missing_people, refugees, death, other_aid, infrastructure_related, transport, buildings, electricity, tools, hospitals, shops, aid_centers, other_infrastructure, weather_related, floods, storm, fire, earthquake, cold, other_weather, direct_report]
Index: []

[0 rows x 40 columns]

In [18]:
category_names = df.iloc[:,4:].columns
category_boolean = (df.iloc[:,4:] != 0).sum().values

In [19]:
category_boolean

array([20094,  4474,   118, 10860,  2084,  1313,   724,   471,   860,
           0,  1672,  2923,  2314,   405,   604,   298,   875,  1194,
        3446,  1705,  1201,  1333,   532,   159,   283,   120,   309,
        1151,  7297,  2155,  2443,   282,  2455,   530,  1376,  5075])

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [16]:
engine = create_engine('sqlite:///DisasterResponse.db')
df.to_sql('MessageAndCategories', engine, index=False)

ValueError: Table 'MessageAndCategories' already exists.

### 8. Use this notebook to complete `etl_pipeline.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `etl_pipeline.py` in the classroom on the `Project Workspace IDE` coming later.